apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-potatoes-deployment
  labels:
    app: rotten-potatoes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rotten-potatoes
  template:
    metadata:
      labels:
        app: rotten-potatoes
    spec:
      containers:
      - name: rotten-potatoes
        image: localhost:5000/kubedev/rotten-potatoes:1.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: mongodb-service
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd
---
apiVersion: v1
kind: Service
metadata:
  name: rotten-potatoes-service
spec:
  type: NodePort
  selector:
    app: rotten-potatoes
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30020